// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, cloudscraper, needle;

  Promise = require('bluebird');

  needle = Promise.promisifyAll(require('needle'));

  cloudscraper = require('cloudscraper');

  module.exports = {
    name: 'kissanime',
    http_options: {
      follow_max: 5
    },
    initialize: function() {
      this.http_options.headers = {
        'Cookie': '',
        'User-Agent': 'Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36'
      };
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return cloudscraper.get('http://kissanime.to', function(err, resp, body) {
            var cookie_string;
            if (err) {
              return reject(err);
            } else {
              cookie_string = resp.request.headers.cookie;
              _this.http_options.headers.cookie = cookie_string;
              return resolve();
            }
          });
        };
      })(this));
    },
    search: {
      page: function(query) {
        var data;
        data = {
          animeName: query,
          genres: '',
          status: ''
        };
        return needle.postAsync('https://kissanime.to/AdvanceSearch', data, this.http_options).get('body');
      },
      list: '.listing tr > td > a',
      row: {
        name: function(el) {
          return el.text().trim();
        },
        url: function(el) {
          return "https://kissanime.to" + el.attr('href');
        }
      }
    },
    series: {
      list: '.listing tr > td > a',
      row: {
        name: function(el) {
          return el.text().trim();
        },
        url: function(el) {
          return "https://kissanime.to" + el.attr('href');
        }
      }
    },
    episode: function($, body) {
      return $('#selectQuality > option').map(function(index) {
        var buf, name, url;
        name = $(this).text();
        url = $(this).attr('value');
        buf = new Buffer(url, 'base64');
        url = buf.toString('utf-8');
        return {
          label: name,
          url: url
        };
      }).get();
    }
  };

}).call(this);
